language: node_js

node_js:
    - "stable"
    - "5"
    - "4"
    - "4.3"

notifications:
    email: false

before_script: npm install

after_success: npm run coverage

branches:
  only:
    - master
    - /^v[0-9].*$/
